Leafwing-Studios/leafwing-website

config.yml
content/about.md
content/projects.md
themes/leafwing/assets/css/common/post-entry.css

Closes #6. Closes #35. Closes #21. Closes #43.

Better info about Leafwing Studios and our projects

---

.github/linters/.markdown-lint.yml
.github/workflows/ci.yml

Runs mdlint and ensures the website builds.

Add basic CI

---

content/blog/_index.md
content/blog/post/test-post.md

This isn't showing up, which proves why we need it. Previously removed in #94.

Add test blog post

---

content/blog/test-post-0.md
content/blog/test-post-1.md
templates/blog-section.html
themes/lws/sass/_text.scss
themes/lws/templates/page.html

This doesn't fix anything, but does record some detective work...

Cleanup work for blog templates

---

templates/index.html

Improve footer

---

sass/_dark-mode.scss
sass/lws.scss
templates/index.html

Followup to #114. What a fool I was, trying to apply the footer style to the footer and fixing that typo.

Fix footer

---

sass/_layout.scss
sass/_pagination.scss
sass/lws.scss
templates/_macros.html
templates/blog-section.html
templates/index.html
templates/tags/single.html

This is massive and bad and a mess. We can fix the resulting problems in followups.

Remove bulma css dependency

---

sass/_colors.scss
sass/_footer.scss
sass/_header.scss
sass/_layout.scss
sass/_table-of-contents.scss
sass/_text.scss
templates/blog-section.html
templates/index.html

Makes the colors prettier (subjective) and better organized + easier to refactor (definitely objective!).

Color cleanup

---

content/team/index.md

Fix broken Twitch link

---

sass/_colors.scss
sass/_table-of-contents.scss

Improve color contrast

---

content/team/index.md

Emails should use mailto links

---

templates/_macros.html

Add link to tags

---

sass/_pagination.scss
sass/lws.scss

Tweak appearance of pagination

---

sass/_blog-cards.scss
sass/_table-of-contents.scss
templates/index.html

Make the ToC prettier

---

sass/lws.scss

Fixes #135. Thanks @TimJentzsch!

Footer should be pushed to bottom

---

content/projects/index.md

Fixes typos in Projects page

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/content.md

Add issue templates

---

sass/_colors.scss

Increase color contrast to improve accessibility

---

sass/_colors.scss
sass/_footer.scss
templates/home.html

Fixes issues opened by @TimJenschtz; see the commit messages for details. Thanks!
Fixes #166. Fixes #169. Fixes #168.

Minor acessibility fixes

---

.github/PULL_REQUEST_TEMPLATE/blog_post.md

Create Blog Post PR template

---

.github/PULL_REQUEST_TEMPLATE.md

Remove fancy features from PR template :(

---

content/blog/game-engine-glue/index.md

Credit to @james7132 for raising this point.
Some interesting discussion [on Discord](https://discord.com/channels/691052431525675048/1000245270627495976/1000539756624629760)

Add note about the ability to cut corners in SGS

---

.github/PULL_REQUEST_TEMPLATE.md
content/blog/debugging-lessons/index.md
content/blog/game-engine-glue/index.md

Debugging lessons blog post

---

content/projects/index.md

Update Emergence related links

---

content/blog/triage-by-controversy/index.md

Add triage-by-controversy blog post

---

content/blog/tyranny-of-nits/index.md

Fix typo in "Tyranny of Nits"

---

content/blog/tyranny-of-nits/index.md

Full credit to @Polostor for finding these. https://github.com/Leafwing-Studios/leafwing-website/pull/239#pullrequestreview-1651964295

Fix nits in Tyranny of Nits

---

content/blog/skeptics-guide-to-machine-learning/index.md

A skeptic's guide to productionizing machine learning

---

content/blog/ecs-gui-framework/index.md

So you want to build an ECS-backed GUI framework
